[build-system]
requires = ["setuptools","setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "portio"
dynamic = ["version","readme"]
description = "PortIO, python low level port I/O for Linux and FreeBSD x86"
requires-python = ">=2.8"
license = "GPL-2.0+"
keywords = []
authors = [
  { name = "Fabrizio Pollastri", email = "mxgbot@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 2",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: Implementation :: CPython",
  "Operating System :: POSIX :: Linux",
  "Operating System :: POSIX :: BSD :: FreeBSD",
  "Topic :: System :: Hardware",
  "Topic :: Software Development :: Libraries",
  "Intended Audience :: Developers",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/fabriziop/portio#readme"
Issues = "https://github.com/fabriziop/portio/issues"
Source = "https://github.com/fabriziop/portio"

[tool.coverage.run]
source_pkgs = ["portio"]
branch = true
parallel = true
omit = [
  "src/temporary/__about__.py",
]

[tool.coverage.paths]
portio = ["*/portio"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.setuptools.dynamic]
readme = {file = "README.rst"}

[tool.setuptools]
py-modules = ["conf","toggle"]

[tool.setuptools_scm]
git_describe_command = ["git","describe","--tags"]

